name: Reusable Docker Build Workflow

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
      dockerhub_image:
        required: true
        type: string
      ghcr_image:
        required: true
        type: string
      image_version_prefix:
        required: false
        type: string
        default: ''
      docker_extra_build_args:
        required: false
        type: string
        default: ''
    secrets:
      dockerhub_username:
        required: true
      dockerhub_password:
        required: true
      ghcr_username:
        required: false
      ghcr_password:
        required: true

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.ghcr_username || github.actor }}
          password: ${{ secrets.ghcr_password }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.dockerhub_image }}
            ${{ inputs.ghcr_image }}
          tags: |
            type=raw,value=${{ inputs.image_version_prefix }}${{ inputs.image_version }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            ${{ inputs.docker_extra_build_args }}
          tags: ${{ steps.meta.outputs.tags }}