name: Reusable Docker Build Workflow

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
      dockerhub_image:
        required: true
        type: string
      ghcr_image:
        required: true
        type: string
      docker_extra_build_args:
        required: false
        type: string
        default: ''
      platforms:
        required: false
        type: string
        default: 'linux/amd64'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      GHCR_USERNAME:
        required: false
      GHCR_PASSWORD:
        required: true

jobs:
  docker-build-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME || github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.dockerhub_image }}
            ${{ inputs.ghcr_image }}
          tags: |
            type=raw,value=${{ inputs.image_version }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: |
            ${{ inputs.platforms }}
          build-args: |
            ${{ inputs.docker_extra_build_args }}
          tags: ${{ steps.meta.outputs.tags }}
