name: Reusable Docker Build Workflow

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
      dockerhub_image:
        required: true
        type: string
      image_version_prefix:
        required: false
        type: string
        default: ''
      docker_extra_build_args:
        required: false
        type: string
        default: ''

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.dockerhub_image }}
          tags: |
            type=raw,value=${{ inputs.image_version_prefix }}${{ inputs.image_version }}_pr${{ github.event.pull_request.number }}_${{ github.head_ref }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            version=${{ inputs.image_version }}
            ${{ inputs.docker_extra_build_args }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Add PR Comment with Image Tag
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🐳 Built Docker image (**version: ${{ inputs.image_version }}**):
            ```sh
            docker pull ${{ steps.meta.outputs.tags }}
            ```