name: Reusable Remove Docker Images Workflow

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
      dockerhub_image:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  docker-remove-test-images:
    if: github.event.action == 'closed'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Docker Registry Image Cleaner
        uses: nstwfdev/docker-registry-image-cleaner@1.0.1
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerhub_repo: ${{ inputs.dockerhub_image }}
          image_prefix: |
            ${{ inputs.image_version }}_pr${{ github.event.pull_request.number }}

      - name: Add PR Comment about cleanup
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🐳 Cleanup test images for current pr (**version: ${{ inputs.image_version }}**):